SeoAnalyzer/SeoAnalyzer/Models/AnalysisParameters.cs
using System.ComponentModel.DataAnnotations;

namespace SeoAnalyzer.Models
{
    public class AnalysisParameters
    {
        [Required(ErrorMessage = "Please, insert text or URL")]
        public string Content { get; set; }

        public bool IsUrl { get; set; }

        public bool IsAnalyzeMetaTags { get; set; }

        public bool IsCountExternalLinks { get; set; }
    }
}

SeoAnalyzer/SeoAnalyzer/Models/AnalysisResult.cs
using System.Collections.Generic;

namespace SeoAnalyzer.Models
{
    public class AnalysisResult
    {
        public Dictionary<string, int> TextAnalysis { get; set; }

        public Dictionary<string, int> MetaTagsAnalysis { get; set; }

        public int ExternalLinksCount { get; set; }
    }
}

SeoAnalyzer/SeoAnalyzer/Controllers/AnalyzerController.cs
using System;
using System.Net;
using System.Web.Mvc;
using SeoAnalyzer.Core;
using SeoAnalyzer.Models;

namespace SeoAnalyzer.Controllers
{
    public class AnalyzerController : Controller
    {   
        [HttpGet]
        public ViewResult Home()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Home(AnalysisParameters parameters)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    return View("Result", new ContentProcessor().Process(parameters));
                }
                catch (WebException ex)
                {
                    if (ex.Status == WebExceptionStatus.NameResolutionFailure)
                    {
                        ModelState.AddModelError("Content", "Provided host name can not be resolved");
                    }

                    if (ex.Status == WebExceptionStatus.Timeout)
                    {
                        ModelState.AddModelError("Content",
                            "No response was received during the time-out period for a request");
                    }
                }

                catch (UriFormatException)
                {
                    ModelState.AddModelError("Content", "Please, insert a correct URI");
                }

                catch (Exception ex)
                {
                    ModelState.AddModelError("Content", ex.Message);
                }
            }

            return View();
        }
    }
}

SeoAnalyzer/SeoAnalyzer/Views/Analyzer/Home.cshtml
@model SeoAnalyzer.Models.AnalysisParameters

@{
    ViewBag.Title = "SEO analyzer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="header-description">
    This application performs a simple SEO analysis of the text.
    It calculates a number of occurrences of each word and also can analyze meta tags (searches for meta element with name="description") and count external links in the text.
    To get started - copy a text in the text area below or insert a URL.
</h4>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="option-group">
        <label for="IsUrl">Use URL:</label>
        @Html.CheckBoxFor(x => x.IsUrl, new { @class = "is-url" })
    </div>

    <div class="option-group count-external-links">
        <label title="Calculate number of external links">Count external links:</label>
        @Html.CheckBoxFor(x => x.IsCountExternalLinks)
    </div>

    <div class="option-group analyze-metatags">
        <label title="Calculate number of uccurences on the page of each word listed in meta tags">Analyze meta tags:</label>
        @Html.CheckBoxFor(x => x.IsAnalyzeMetaTags)
    </div>

    <div class="form-group">
        @Html.TextAreaFor(x => x.Content, new { @class = "default-tb-size"})
        @Html.ValidationMessageFor(x => x.Content)
    </div>

    <input class="btn btn-primary" type="submit" value="Run" />
}


<script>
    $(function () {
        $('.is-url').change(function () {
            if (this.checked) {
                $('.analyze-metatags').fadeIn().css("display", "inline-block");
                $('.count-external-links').fadeIn().css("display", "inline-block");

            } else {
                $('.analyze-metatags').fadeOut();
                $('.count-external-links').fadeOut();
            }
        });

        $('.is-url').trigger('change');

    });
</script>

SeoAnalyzer/SeoAnalyzer/Views/Analyzer/OccurenceTable.cshtml
@model Dictionary<string, int>

<table class="table-striped table-custom occurence-table">
    <thead>
        <tr>
            <th>
                <label class="column-name">Word</label>
            </th>
            <th class='sort-default'>
                <label class="column-name">Count</label>
            </th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Key</td>
            <td>@item.Value</td>
        </tr>
    }
</table>

SeoAnalyzer/SeoAnalyzer/Views/Analyzer/Result.cshtml
@model SeoAnalyzer.Models.AnalysisResult

@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/tablesort.number.js"></script>

@Html.ActionLink("Start new analysis", "Home", "Analyzer", null, new { @class = "start-link" })

@if (Model.TextAnalysis != null && Model.TextAnalysis.Any())
{
    <h3 class="result-description">Text analysis</h3>
  
    Html.RenderPartial("OccurenceTable", Model.TextAnalysis); 
}

@if (Model.MetaTagsAnalysis != null && Model.MetaTagsAnalysis.Any())
{
    <h3 class="result-description">Meta Tags analysis</h3>

    Html.RenderPartial("OccurenceTable", Model.MetaTagsAnalysis);
}

@if (Model.ExternalLinksCount > 0)
{
    <h3 class="result-description">External links:</h3>
    <h5>@Model.ExternalLinksCount</h5>
}


<script type="text/javascript">
    $(function () {

        var $tablesForSorting = $('.occurence-table');

        for (var i = 0; i < $tablesForSorting.length; i++) {
            new Tablesort($tablesForSorting[i], { descending: true });
        }
    });
</script>

SeoAnalyzer/SeoAnalyzer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrapCss")
    @Styles.Render("~/Content/Custom/Custom.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/tablesort")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    <b class="app-title">SEO Analyzer</b>

    @RenderBody()
</body>
</html>